apiVersion: v1
kind: PersistentVolume
metadata:
  name: net-pv
spec:
  volumeMode: Filesystem
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: "net"
  hostPath:
    path: "/Users/tony/Desktop/app"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: net-pvc
spec:
  storageClassName: "net"
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: net-deployment
spec:
  selector:
    matchLabels:
      app: net-deployment
  template:
    metadata:
      labels:
        app: net-deployment
    spec:
      containers:
      - name: net-deployment
        image: tony3527657/net6demo
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: /app/logs
            name: log-volume
          - mountPath: /app/images
            name: image-volume
          - mountPath: /app/firebase_credential.json
            subPath: firebase_credential.json
            name: firebase-config-volume
      volumes:
        - name: log-volume
          persistentVolumeClaim:
            claimName: net-pvc
          # hostPath:
            # path: /Users/tony/Desktop/app
        - name: image-volume
          persistentVolumeClaim:
            claimName: net-pvc
        - name: firebase-config-volume
          configMap:
            name: firebase-config

---

apiVersion: v1
kind: Service
metadata:
  name: net-cluster
spec:
  selector:
    app: net-deployment
  ports:
  - port: 80
    targetPort: 80
