apiVersion: apps/v1
kind: Deployment
metadata:
  name: net-deployment
spec:
  selector:
    matchLabels:
      app: net-deployment
  template:
    metadata:
      labels:
        app: net-deployment
    spec:
      containers:
      - name: net-deployment
        image: tony3527657/net6demo
        ports:
        - containerPort: 80